apiVersion: v1
kind: Pod
metadata:
  name: hello-pod
  labels:
    name: hello-pod
    zone: prod
    version: v1
spec:
  containers:
  - name: hello-pod
    image: nigelpoulton/k8sbook:1.0
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
